name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Validation composer
      run: composer validate

    - name: Packages en composer cache
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Installation des dependances
      run: composer install --prefer-dist --no-progress
      
    - name: Lancement des tests
      run: make test
    
    - name : code_coverage
      run: XDEBUG_MODE=coverage ./vendor/bin/phpunit tst --coverage-cobertura ./log/coverage_cobertura.xml

                    
    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ./log/coverage_cobertura.xml
        badge: true
        format: markdown
        output: both
        thresholds: 50 75 

    - name : test visualisation
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

    #- name: PHP Code Sniffer
    #  uses: php-actions/phpcs@v1
    #  with:
    #    path: lib/

    - name: PHP Mess Detector
      uses: php-actions/phpmd@v1
      with:
        path: lib/
        output: text
        ruleset: ruleset.xml

    #- name: PHP Stan
    #  uses: php-actions/phpstan@v3
    #  with:
    #    path: lib/

    - name: Delete vendor
      run: rm -rf ./vendor
    
    - name: Envoi des fichiers
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.auto_prod_adresse }}
        port : ${{ secrets.auto_prod_port }}
        username: ${{ secrets.auto_prod_username }}
        password: ${{ secrets.auto_prod_password }}
        server-dir: /www/
        exclude: | 
          **/.git*
